# Site settings
title: Steve Myles
email: steve@mylesandmyles.info
url: https://s.mylesandmyles.info/
blog-url: https://s.mylesandmyles.info/blog/
description: "Steve Myles, some guy from Texas"
skills: "analytics and slow-speed distance running"
meta_author: Steve Myles
future: true

# Google webmaster tools
google_verify: v249ifvo2RPEG6ai3LJgSAG7PRDntewxOW37aBgrhZY

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: lognormality

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3a88db
  primary-rgb: "58,136,219"
  secondary: 39383d
  secondary-dark: 57565e

# Footer settings
footer:
  copyright: <a href="mailto:steve@mylesandmyles.info">Steve Myles</a>. <a href="/license/">Some rights reserved</a>.
  social: Me Elsewhere
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stevenmyles
  - title: github
    url: https://github.com/scumdogsteev
  - title: flickr
    url: https://www.flickr.com/photos/scumdogsteev/
  - title: instagram
    url: https://www.instagram.com/scumdogsteev/
  - title: youtube
    url: https://www.youtube.com/user/scumdogsteev	
  - title: soundcloud
    url: https://soundcloud.com/scumdogsteev
  - title: tumblr
    url: https://steve.mylesandmyles.info/
  - title: lastfm
    url: https://www.last.fm/user/scumdogsteev  

# Credits content
credits: 'Theme = <a href="http://jekyllthemes.org/themes/freelancer/">Freelancer</a> by <a href="https://startbootstrap.com">Start Bootstrap</a>.  Hosting by <a href="https://pages.github.com/">GitHub Pages</a>.'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/page-:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    category: '/blog/:name/'
  
plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  